/usr/lib/python3/dist-packages/_pytest/main.py:306: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: terminalreporter, Hook: pytest_sessionfinish
KeyboardInterrupt: 
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config.hook.pytest_sessionfinish(
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3/dist-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
                     ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 192, in console_main
    code = main()
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 169, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        config=config
        ^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3/dist-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pluggy/_callers.py", line 138, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/usr/lib/python3/dist-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 318, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 306, in wrap_session
    config.hook.pytest_sessionfinish(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        session=session, exitstatus=session.exitstatus
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3/dist-packages/pluggy/_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pluggy/_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pluggy/_callers.py", line 155, in _multicall
    teardown[0].send(outcome)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3/dist-packages/_pytest/terminal.py", line 857, in pytest_sessionfinish
    outcome.get_result()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3/dist-packages/pluggy/_result.py", line 99, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/lib/python3/dist-packages/pluggy/_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
  File "/home/komi/.local/lib/python3.13/site-packages/xdist/dsession.py", line 99, in pytest_sessionfinish
    nm.teardown_nodes()
    ~~~~~~~~~~~~~~~~~^^
  File "/home/komi/.local/lib/python3.13/site-packages/xdist/workermanage.py", line 117, in teardown_nodes
    self.group.terminate(self.EXIT_TIMEOUT)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/komi/.local/lib/python3.13/site-packages/execnet/multi.py", line 237, in terminate
    safe_terminate(
    ~~~~~~~~~~~~~~^
        self.execmodel,
        ^^^^^^^^^^^^^^^
    ...<4 lines>...
        ],
        ^^
    )
    ^
  File "/home/komi/.local/lib/python3.13/site-packages/execnet/multi.py", line 348, in safe_terminate
    reply.get()
    ~~~~~~~~~^^
  File "/home/komi/.local/lib/python3.13/site-packages/execnet/gateway_base.py", line 327, in get
    self.waitfinish(timeout)
    ~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/komi/.local/lib/python3.13/site-packages/execnet/gateway_base.py", line 334, in waitfinish
    if not self._result_ready.wait(timeout):
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/threading.py", line 659, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.13/threading.py", line 359, in wait
    waiter.acquire()
    ~~~~~~~~~~~~~~^^
KeyboardInterrupt
